import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  renderToStream,
} from "@react-pdf/renderer";

// Styles matched to the original pdf-lib design
const styles = StyleSheet.create({
  page: {
    padding: 60,
    backgroundColor: "#ffffff",
  },
  headerBar: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 45,
    backgroundColor: "#0a1628", // NAVY
  },
  headerContainer: {
    flexDirection: "row",
    alignItems: "baseline",
    marginTop: 15,
  },
  logo: {
    fontSize: 18,
    color: "#f97316", // ORANGE
    fontWeight: "bold",
  },
  subtitle: {
    fontSize: 9,
    color: "#9ca3af", // LIGHT_GRAY
    marginLeft: 10,
  },
  divider: {
    borderBottomWidth: 1,
    borderBottomColor: "#f97316",
    marginVertical: 20,
  },
  institution: {
    fontSize: 12,
    color: "#0a1628",
    fontWeight: "bold",
    marginBottom: 30,
  },
  body: {
    fontSize: 11,
    color: "#374151", // DARK_GRAY
    lineHeight: 1.5,
  },
  footerContainer: {
    position: "absolute",
    bottom: 60,
    left: 60,
    right: 60,
    borderTopWidth: 0.5,
    borderTopColor: "#9ca3af",
    paddingTop: 15,
  },
  footerText: {
    fontSize: 8,
    color: "#9ca3af",
  },
});

export async function generateLetterPdf(
  letterText: string,
  institution: string,
  heirName: string
): Promise<Uint8Array> {
  const LetterDocument = (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.headerBar} fixed />

        <View style={styles.headerContainer} fixed>
          <Text style={styles.logo}>AntimAI</Text>
          <Text style={styles.subtitle}>
            Post-Death Administrative Assistant
          </Text>
        </View>

        <View style={styles.divider} fixed />

        <Text style={styles.institution}>RE: {institution}</Text>

        <Text style={styles.body}>{letterText}</Text>

        <View style={styles.footerContainer} fixed>
          <Text style={styles.footerText}>
            Generated by AntimAI — This is a draft letter. Please review before
            submission.
          </Text>
        </View>
      </Page>
    </Document>
  );

  const stream = await renderToStream(LetterDocument);
  
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    stream.on("data", (chunk) => chunks.push(Buffer.from(chunk)));
    stream.on("error", (err) => reject(err));
    stream.on("end", () => {
      const buffer = Buffer.concat(chunks);
      resolve(new Uint8Array(buffer));
    });
  });
}
